# Generated by Django 5.1.3 on 2024-12-01 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muqaddar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backtest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('condition', models.TextField(default='default condition')),
            ],
        ),
        migrations.CreateModel(
            name='Screener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('condition', models.TextField(default='default condition')),
            ],
        ),
        migrations.DeleteModel(
            name='TrackerData',
        ),
        migrations.DeleteModel(
            name='URLTracker',
        ),
    ]
