# Generated by Django 5.1.3 on 2024-12-02 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muqaddar', '0003_condition'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screener_name', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('stocks', models.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name='Backtest',
        ),
        migrations.DeleteModel(
            name='Condition',
        ),
        migrations.DeleteModel(
            name='Screener',
        ),
    ]
