# Generated by Django 5.1.3 on 2024-12-02 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muqaddar', '0004_screenerhistory_delete_backtest_delete_condition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nsecode', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('bsecode', models.CharField(blank=True, max_length=20, null=True)),
                ('per_chg', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.BigIntegerField()),
            ],
        ),
    ]
