# Generated by Django 5.1.3 on 2024-12-02 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muqaddar', '0005_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='screener',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
