# Generated by Django 5.1.3 on 2024-12-03 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muqaddar', '0009_screener'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Screener',
        ),
    ]
