# Generated by Django 5.1.3 on 2024-12-18 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muqaddar', '0010_delete_screener'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='alert_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='performance',
            name='alert_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
