# Generated by Django 5.1.3 on 2024-12-19 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muqaddar', '0011_performance_alert_sent_performance_alert_sent_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('screener_name', models.CharField(max_length=100)),
                ('initial_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('triggered_at', models.DateTimeField()),
                ('alert_sent', models.BooleanField(default=False)),
                ('alert_sent_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
