# Generated by Django 5.1.3 on 2024-12-23 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muqaddar', '0012_stockalert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance',
            name='current_price',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='percent_change',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='time_elapsed',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='timeframe',
        ),
        migrations.AlterField(
            model_name='performance',
            name='initial_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='performance',
            name='symbol',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='performance',
            name='triggered_at',
            field=models.DateTimeField(),
        ),
    ]
