# Generated by Django 5.1.3 on 2024-12-23 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muqaddar', '0013_remove_performance_current_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performance',
            old_name='alert_sent_at',
            new_name='last_alert_sent_time',
        ),
        migrations.AddField(
            model_name='performance',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='performance',
            name='symbol',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='performance',
            name='triggered_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
