# Generated by Django 5.1.3 on 2024-12-23 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muqaddar', '0015_remove_performance_current_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performance',
            old_name='last_alert_sent_time',
            new_name='alert_sent_at',
        ),
    ]
