# Generated by Django 5.1.3 on 2024-12-26 04:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muqaddar', '0016_rename_last_alert_sent_time_performance_alert_sent_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockAlert',
        ),
        migrations.AddField(
            model_name='performance',
            name='timeframe',
            field=models.CharField(default='N/A', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='performance',
            name='initial_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='performance',
            name='symbol',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='performance',
            name='triggered_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
